# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

r_binary_packages:
  - testthat
  - covr

warnings_are_errors: true

sudo: required

cran: http://cran.rstudio.com/

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE, ...=list(quiet=FALSE))'

# notifications:
#   email:
#     on_success: brodie.gaslam@yahoo.com
#     on_failure: brodie.gaslam@yahoo.com
